baseURL = "https://plevy.fr"
languageCode = "en"
title = "Pierre Lévy"
theme = "plevy"
defaultContentLanguage = "en"
ignoreErrors = ["error-disable-taxonomy"]
copyright = "plevy.fr"

[Params]
favicon = "icon.png"

[deployement]
order = [".webp", ".jpg$", ".gif$"]
  [deployment.targets]
  # An arbitrary name for this target.
  name = "plevydeploy"
  [deployment.matchers]
  # Set custom content type for /sitemap.xml 
  pattern = "^sitemap\\.xml$"
  contentType = "application/xml"
  gzip = true
  
[build]
  useResourceCacheWhen = "never"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true
privacyEnhanced = true

[privacy.youtube]
disable = true
privacyEnhanced = true

[minify]
minifyOutput = true
merge = "deep"