baseURL = "https://plevy.fr"
locale = "fr-FA"
title = "Pierre Lévy"
theme = "plevy26_list"
defaultContentLanguage = "fr"
ignoreErrors = ["error-disable-taxonomy", "warning-goldmark-raw-html"]

DefaultContentLanguage = "fr"
copyright = "plevy.fr"

[Params]
favicon = "icon.png"
removePathAccents = true

[deployement]
order = [".webp", ".jpg$", ".gif$"]
  [deployment.targets]
  # An arbitrary name for this target.
  name = "plevy-deploy"
  [deployment.matchers]
  # Set custom content type for /sitemap.xml
  pattern = "^sitemap\\.xml$"
  contentType = "application/xml"
  gzip = true

[build]
  [build.buildStats]
    enable = true
  useResourceCacheWhen = "never"

[security]
  # Allows both Markdown and HTML files in the content folder
  allowContent = ['^text/markdown$', '^text/html$']

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.x]
disable = true

[privacy.vimeo]
disable = true
privacyEnhanced = true

[privacy.youtube]
disable = true
privacyEnhanced = true

[minify]
minifyOutput = true
merge = "deep"

[languages]
  [languages.fr]
    label = "FR"
    locale = "fr-FA"
    weight = 1
  [languages.en]
    label = "EN"
    locale = "en-GB"
    weight = 2
  [languages.jp]
    label = "JP"
    locale = "jp-JA"
    weight = 3
